server.port=8080

# 1. Name the service so Eureka knows who this is
spring.application.name=movie-catalogue-service

# 2. Tell this app where to find the Eureka Server registry
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# 3. Bypass the Docker Desktop hostname issue we ran into
eureka.instance.prefer-ip-address=true

# Keep this true so the app can download the map and find user-info-service
eureka.client.fetch-registry=true

# Turn this false so the catalogue app completely disappears from the Eureka dashboard
eureka.client.register-with-eureka=false